# Auto-generated by renpy-agent. Project-specific options file.

define config.name = _("{{TITLE}}")

define gui.show_name = True

define config.version = "0.1"

define gui.about = _p("""
Generated by renpy-agent (Stage A placeholder build).
""")

define build.name = "{{BUILD_NAME}}"

define config.has_sound = True
define config.has_music = True
define config.has_voice = True

define config.enter_transition = dissolve
define config.exit_transition = dissolve
define config.intra_transition = dissolve
define config.after_load_transition = None
define config.end_game_transition = None

define config.window_icon = "gui/window_icon.png"

define build.include_old_themes = False
