import { describe, expect, it } from 'vitest';
import {
  assignCharacterIdentifiers,
  assignSceneIdentifiers,
  generateGameProject,
  logicalKeyForCharacter,
  logicalKeyForScene,
  renderScriptRpy,
} from './coder.js';
import type { PlannerOutput, StoryboarderOutput } from './types.js';
import type { AssetRegistryFile } from '../assets/registry.js';

const PLANNER_FIXTURE: PlannerOutput = {
  projectTitle: '樱花夜',
  genre: 'romance',
  tone: 'tender',
  characters: [
    { name: '白樱', description: 'protagonist', visualDescription: 'pink hair' },
    { name: 'Mia', description: 'friend', visualDescription: 'blue eyes' },
  ],
  scenes: [
    { name: 'sakura_night', description: 'night under cherry blossoms' },
    { name: 'classroom', description: 'empty classroom' },
  ],
  chapterOutline: 'a confession under sakura',
};

const STORYBOARDER_FIXTURE: StoryboarderOutput = {
  shots: [
    {
      shotNumber: 1,
      description: 'whispers under sakura',
      characters: ['白樱'],
      sceneName: 'sakura_night',
      staging: 'enter',
      transforms: 'stand breathing',
      transition: 'fade',
      effects: 'sakura particles',
      dialogueLines: [
        { speaker: '白樱', text: '你又来了。' },
        { speaker: 'narrator', text: '她的声音像晚风。' },
      ],
    },
    {
      shotNumber: 2,
      description: 'lean in close',
      characters: ['白樱'],
      sceneName: 'sakura_night',
      staging: 'front',
      transforms: 'lean in',
      transition: 'dissolve',
      dialogueLines: [{ speaker: '白樱', text: '别走。' }],
    },
    {
      shotNumber: 3,
      description: 'classroom flashback',
      characters: ['Mia'],
      sceneName: 'classroom',
      staging: 'lookup',
      transforms: 'heart_pulse',
      transition: 'fade',
      dialogueLines: [{ speaker: 'Mia', text: 'Remember the spring?' }],
    },
  ],
};

describe('assignCharacterIdentifiers', () => {
  it('creates unique ASCII idents and avoids narrator slot', () => {
    const idents = assignCharacterIdentifiers(['白樱', 'narrator', '白樱']);
    const values = Array.from(idents.values());
    expect(new Set(values).size).toBe(values.length);
    expect(values).not.toContain('v');
  });

  it('renames clashing idents with numeric suffix', () => {
    const idents = assignCharacterIdentifiers(['Hana', 'Hana!']);
    const values = Array.from(idents.values());
    expect(values).toEqual(['hana', 'hana2']);
  });

  it('falls back to a safe base when name has no ASCII', () => {
    const idents = assignCharacterIdentifiers(['白樱', '黒猫']);
    for (const v of idents.values()) {
      expect(v).toMatch(/^[a-z_][a-z0-9_]*$/);
    }
  });
});

describe('assignSceneIdentifiers', () => {
  it('sanitizes scene names into ident-safe slugs', () => {
    const idents = assignSceneIdentifiers(['Sakura Night!', '教室']);
    const values = Array.from(idents.values());
    expect(values[0]).toBe('sakura_night');
    expect(values[1]).toMatch(/^[a-z_][a-z0-9_]*$/);
  });
});

describe('renderScriptRpy', () => {
  const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE);

  it('emits a header, image defs, character defs, transforms and a start label', () => {
    expect(script).toContain('Auto-generated by renpy-agent');
    expect(script).toContain('image bg_sakura_night = Solid(');
    expect(script).toContain('image bg_classroom = Solid(');
    expect(script).toMatch(/define \w+ = Character\("白樱"/);
    expect(script).toContain('define v = Character(None');
    expect(script).toContain('transform stand:');
    expect(script).toContain('label start:');
  });

  it('switches backgrounds when scene changes and holds when it does not', () => {
    const sceneLines = script.split('\n').filter((l) => l.includes('scene bg_'));
    expect(sceneLines[0]).toContain('scene bg_sakura_night');
    expect(sceneLines[1]).toContain('scene bg_classroom');
    // Only two scene switches + one final bg_black
    expect(sceneLines).toHaveLength(3);
    expect(sceneLines[2]).toContain('scene bg_black');
  });

  it('shows particles when effects mention sakura', () => {
    expect(script).toContain('show sakura');
  });

  it('applies heart_pulse layer transform when storyboard mentions it', () => {
    expect(script).toContain('show layer master at heart_pulse');
  });

  it('emits narrator dialogue using the v character', () => {
    expect(script).toMatch(/^ {4}v "她的声音像晚风。"/m);
  });

  it('escapes double quotes inside dialogue', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'x',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'enter',
          transforms: 'stand',
          transition: 'none',
          dialogueLines: [{ speaker: '白樱', text: 'She said "hi"' }],
        },
      ],
    };
    const out = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(out).toContain('"She said \\"hi\\""');
  });
});

describe('generateGameProject', () => {
  it('produces four .rpy files with template substitution', async () => {
    const files = await generateGameProject({
      planner: PLANNER_FIXTURE,
      storyboarder: STORYBOARDER_FIXTURE,
    });
    expect(files.scriptRpy).toContain('label start:');
    expect(files.optionsRpy).toContain(`define config.name = _("${PLANNER_FIXTURE.projectTitle}")`);
    expect(files.optionsRpy).not.toContain('{{TITLE}}');
    expect(files.guiRpy.length).toBeGreaterThan(100);
    expect(files.screensRpy.length).toBeGreaterThan(100);
  });
});

describe('renderScriptRpy with AssetRegistry (Stage B binding)', () => {
  it('uses real asset paths when registry has ready entries', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'pid1',
          logicalKey: logicalKeyForScene('sakura_night'),
          assetType: 'scene_background',
          realAssetLocalPath: 'images/bg/sakura_night.png',
          remoteAssetUri: 'https://cdn/s.png',
          status: 'ready',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
        {
          placeholderId: 'pid2',
          logicalKey: logicalKeyForCharacter('白樱'),
          assetType: 'character_main',
          realAssetLocalPath: 'images/char/baiying.png',
          remoteAssetUri: 'https://cdn/c.png',
          status: 'ready',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).toContain('image bg_sakura_night = "images/bg/sakura_night.png"');
    expect(script).toMatch(/image sprite_\w+ = "images\/char\/baiying\.png"/);
    // Scene without a ready asset still falls back to Solid
    expect(script).toContain('image bg_classroom = Solid(');
  });

  it('ignores entries whose status != ready', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'p',
          logicalKey: logicalKeyForCharacter('白樱'),
          assetType: 'character_main',
          realAssetLocalPath: 'images/char/wip.png',
          remoteAssetUri: 'https://cdn/c.png',
          status: 'generating',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).not.toContain('images/char/wip.png');
  });
});
