import { describe, expect, it } from 'vitest';
import {
  assignCharacterIdentifiers,
  assignSceneIdentifiers,
  generateGameProject,
  renderScriptRpy,
} from './coder.js';
import {
  logicalKeyForBgm,
  logicalKeyForCharacter,
  logicalKeyForCutscene,
  logicalKeyForScene,
  logicalKeyForSfx,
  logicalKeyForVoiceLine,
} from '../assets/logical-key.js';
import type { PlannerOutput, StoryboarderOutput } from './types.js';
import type { AssetRegistryFile } from '../assets/registry.js';

const PLANNER_FIXTURE: PlannerOutput = {
  projectTitle: '樱花夜',
  genre: 'romance',
  tone: 'tender',
  characters: [
    { name: '白樱', description: 'protagonist', visualDescription: 'pink hair' },
    { name: 'Mia', description: 'friend', visualDescription: 'blue eyes' },
  ],
  scenes: [
    { name: 'sakura_night', description: 'night under cherry blossoms' },
    { name: 'classroom', description: 'empty classroom' },
  ],
  chapterOutline: 'a confession under sakura',
};

const STORYBOARDER_FIXTURE: StoryboarderOutput = {
  shots: [
    {
      shotNumber: 1,
      description: 'whispers under sakura',
      characters: ['白樱'],
      sceneName: 'sakura_night',
      staging: 'solo_center',
      transform: 'stand',
      transition: 'fade',
      effects: ['sakura'],
      dialogueLines: [
        { speaker: '白樱', text: '你又来了。' },
        { speaker: 'narrator', text: '她的声音像晚风。' },
      ],
    },
    {
      shotNumber: 2,
      description: 'lean in close',
      characters: ['白樱'],
      sceneName: 'sakura_night',
      staging: 'solo_center',
      transform: 'front',
      transition: 'dissolve',
      effects: [],
      dialogueLines: [{ speaker: '白樱', text: '别走。' }],
    },
    {
      shotNumber: 3,
      description: 'classroom flashback',
      characters: ['Mia'],
      sceneName: 'classroom',
      staging: 'solo_center',
      transform: 'heart_pulse',
      transition: 'fade',
      effects: [],
      dialogueLines: [{ speaker: 'Mia', text: 'Remember the spring?' }],
    },
  ],
};

describe('assignCharacterIdentifiers', () => {
  it('creates unique ASCII idents and avoids narrator slot', () => {
    const idents = assignCharacterIdentifiers(['白樱', 'narrator', '白樱']);
    const values = Array.from(idents.values());
    expect(new Set(values).size).toBe(values.length);
    expect(values).not.toContain('v');
  });

  it('renames clashing idents with numeric suffix', () => {
    const idents = assignCharacterIdentifiers(['Hana', 'Hana!']);
    const values = Array.from(idents.values());
    expect(values).toEqual(['hana', 'hana2']);
  });

  it('falls back to a safe base when name has no ASCII', () => {
    const idents = assignCharacterIdentifiers(['白樱', '黒猫']);
    for (const v of idents.values()) {
      expect(v).toMatch(/^[a-z_][a-z0-9_]*$/);
    }
  });
});

describe('assignSceneIdentifiers', () => {
  it('sanitizes scene names into ident-safe slugs', () => {
    const idents = assignSceneIdentifiers(['Sakura Night!', '教室']);
    const values = Array.from(idents.values());
    expect(values[0]).toBe('sakura_night');
    expect(values[1]).toMatch(/^[a-z_][a-z0-9_]*$/);
  });
});

describe('renderScriptRpy', () => {
  const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE);

  it('emits a header, image defs, character defs, transforms and a start label', () => {
    expect(script).toContain('Auto-generated by renpy-agent');
    expect(script).toContain('image bg_sakura_night = Solid(');
    expect(script).toContain('image bg_classroom = Solid(');
    expect(script).toMatch(/define \w+ = Character\("白樱"/);
    expect(script).toContain('define v = Character(None');
    expect(script).toContain('transform stand:');
    expect(script).toContain('label start:');
  });

  it('switches backgrounds when scene changes and holds when it does not', () => {
    const sceneLines = script.split('\n').filter((l) => l.includes('scene bg_'));
    expect(sceneLines[0]).toContain('scene bg_sakura_night');
    expect(sceneLines[1]).toContain('scene bg_classroom');
    // Only two scene switches + one final bg_black
    expect(sceneLines).toHaveLength(3);
    expect(sceneLines[2]).toContain('scene bg_black');
  });

  it('shows particles when effects mention sakura', () => {
    expect(script).toContain('show sakura');
  });

  it('applies heart_pulse layer transform when storyboard mentions it', () => {
    expect(script).toContain('show layer master at heart_pulse');
  });

  it('emits narrator dialogue using the v character', () => {
    expect(script).toMatch(/^ {4}v "她的声音像晚风。"/m);
  });

  it('escapes double quotes inside dialogue', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'x',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'stand',
          transition: 'none',
          effects: [],
          dialogueLines: [{ speaker: '白樱', text: 'She said "hi"' }],
        },
      ],
    };
    const out = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(out).toContain('"She said \\"hi\\""');
  });
});

describe('generateGameProject', () => {
  it('produces four .rpy files with template substitution', async () => {
    const files = await generateGameProject({
      planner: PLANNER_FIXTURE,
      storyboarder: STORYBOARDER_FIXTURE,
    });
    expect(files.scriptRpy).toContain('label start:');
    expect(files.optionsRpy).toContain(`define config.name = _("${PLANNER_FIXTURE.projectTitle}")`);
    expect(files.optionsRpy).not.toContain('{{TITLE}}');
    expect(files.guiRpy.length).toBeGreaterThan(100);
    expect(files.screensRpy.length).toBeGreaterThan(100);
  });
});

describe('renderScriptRpy with AssetRegistry (Stage B binding)', () => {
  it('uses real asset paths when registry has ready entries', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'pid1',
          logicalKey: logicalKeyForScene('sakura_night'),
          assetType: 'scene_background',
          realAssetLocalPath: 'images/bg/sakura_night.png',
          remoteAssetUri: 'https://cdn/s.png',
          status: 'ready',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
        {
          placeholderId: 'pid2',
          logicalKey: logicalKeyForCharacter('白樱'),
          assetType: 'character_main',
          realAssetLocalPath: 'images/char/baiying.png',
          remoteAssetUri: 'https://cdn/c.png',
          status: 'ready',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).toContain('image bg_sakura_night = "images/bg/sakura_night.png"');
    expect(script).toMatch(/image sprite_\w+ = "images\/char\/baiying\.png"/);
    // Scene without a ready asset still falls back to Solid
    expect(script).toContain('image bg_classroom = Solid(');
  });

  it('renders cutscene shots as placeholder caption when no video is ready', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'opening title sweep',
          characters: [],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'reset',
          transition: 'fade',
          effects: [],
          cutscene: { kind: 'transition', motionPrompt: 'slow dolly through cherry blossoms' },
          dialogueLines: [{ speaker: 'narrator', text: '春の夜、ひらり。' }],
        },
        {
          shotNumber: 2,
          description: 'first words after the cut',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'stand',
          transition: 'dissolve',
          effects: [],
          dialogueLines: [{ speaker: '白樱', text: '你来了。' }],
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(script).toContain('cutscene: transition');
    expect(script).toContain('scene bg_black with fade');
    expect(script).toContain('▶ Cutscene placeholder');
    // no movie_cutscene line when registry missing
    expect(script).not.toContain('renpy.movie_cutscene');
    // after a cutscene, the next non-cutscene shot re-issues its scene
    const sceneLines = script.split('\n').filter((l) => l.trim().startsWith('scene bg_'));
    expect(sceneLines.some((l) => l.includes('bg_sakura_night'))).toBe(true);
  });

  it('renders movie_cutscene when registry has a ready cutscene asset', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'confession CG',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'front',
          transition: 'fade',
          effects: [],
          cutscene: { kind: 'reference', motionPrompt: 'tearful embrace' },
          dialogueLines: [{ speaker: 'narrator', text: 'それは誓い。' }],
        },
      ],
    };
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'cutscene:cutscene:shot_1',
          logicalKey: logicalKeyForCutscene(1),
          assetType: 'cutscene',
          realAssetLocalPath: 'videos/cut/shot_1.mp4',
          remoteAssetUri: 'https://cdn/confession.mp4',
          status: 'ready',
          updatedAt: '2026-04-23T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, sb, registry);
    expect(script).toContain('$ renpy.movie_cutscene("videos/cut/shot_1.mp4")');
    expect(script).not.toContain('▶ Cutscene placeholder');
  });

  it('ignores entries whose status != ready', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'p',
          logicalKey: logicalKeyForCharacter('白樱'),
          assetType: 'character_main',
          realAssetLocalPath: 'images/char/wip.png',
          remoteAssetUri: 'https://cdn/c.png',
          status: 'generating',
          updatedAt: '2026-04-22T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).not.toContain('images/char/wip.png');
  });
});

describe('renderScriptRpy audio + UI insertion (v0.5)', () => {
  it('inserts `play music` after scene header when bgm is ready', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'bgm:sakura_night',
          logicalKey: logicalKeyForBgm('sakura_night'),
          assetType: 'bgm_track',
          realAssetLocalPath: 'audio/bgm/sakura_night.mp3',
          remoteAssetUri: 'https://cdn/bgm.mp3',
          status: 'ready',
          updatedAt: '2026-04-25T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).toContain('play music "audio/bgm/sakura_night.mp3" fadeout 1.0');
    // When classroom bgm missing, no play music line for that scene.
    const playMusicCount = (script.match(/play music /g) ?? []).length;
    expect(playMusicCount).toBe(1);
  });

  it('does not insert `play music` when no bgm registered', () => {
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE);
    expect(script).not.toContain('play music');
  });

  it('inserts `voice` before a dialogue line when voice_line is ready', () => {
    // First shot is shotNumber=1, first dialogue line is index 0.
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'voice:shot_1:line_0',
          logicalKey: logicalKeyForVoiceLine(1, 0),
          assetType: 'voice_line',
          realAssetLocalPath: 'audio/voice/shot_1/line_0.mp3',
          remoteAssetUri: 'https://cdn/v.mp3',
          status: 'ready',
          updatedAt: '2026-04-25T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).toContain('voice "audio/voice/shot_1/line_0.mp3"');
    // voice line sits directly before its say — find its index and confirm the
    // next non-blank line is a say statement.
    const lines = script.split('\n');
    const voiceIdx = lines.findIndex((l) => l.includes('voice "audio/voice/shot_1/line_0.mp3"'));
    expect(voiceIdx).toBeGreaterThan(-1);
    expect(lines[voiceIdx + 1]).toMatch(/"你又来了。"/);
  });

  it('inserts `play sound` at shot entry when sfx enter cue is ready', () => {
    const registry: AssetRegistryFile = {
      version: 1,
      entries: [
        {
          placeholderId: 'sfx:shot_1:enter',
          logicalKey: logicalKeyForSfx(1, 'enter'),
          assetType: 'sfx',
          realAssetLocalPath: 'audio/sfx/shot_1_enter.mp3',
          remoteAssetUri: 'https://cdn/s.mp3',
          status: 'ready',
          updatedAt: '2026-04-25T00:00:00.000Z',
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE, registry);
    expect(script).toContain('play sound "audio/sfx/shot_1_enter.mp3"');
  });
});

describe('renderScriptRpy — v0.7 enum transforms', () => {
  it('emits ATL definitions for all 6 new transforms', () => {
    const script = renderScriptRpy(PLANNER_FIXTURE, STORYBOARDER_FIXTURE);
    expect(script).toContain('transform pan_left:');
    expect(script).toContain('transform pan_right:');
    expect(script).toContain('transform fade_in:');
    expect(script).toContain('transform fade_out:');
    expect(script).toContain('transform shake:');
    expect(script).toContain('transform blink:');
  });

  it('dispatches pan_left to `at pan_left` on sprite show', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'camera pans to find her',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_left',
          transform: 'pan_left',
          transition: 'fade',
          effects: [],
          dialogueLines: [{ speaker: '白樱', text: '...' }],
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(script).toMatch(/show sprite_\w+ at pan_left/);
  });

  it('dispatches fade_in to `at fade_in` on sprite show', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'she materializes',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'fade_in',
          transition: 'dissolve',
          effects: [],
          dialogueLines: [{ speaker: '白樱', text: '来了。' }],
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(script).toMatch(/show sprite_\w+ at fade_in/);
  });

  it('dispatches shake to `at shake` on sprite show', () => {
    const sb: StoryboarderOutput = {
      shots: [
        {
          shotNumber: 1,
          description: 'impact beat',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'solo_center',
          transform: 'shake',
          transition: 'none',
          effects: [],
          dialogueLines: [{ speaker: '白樱', text: '!' }],
        },
      ],
    };
    const script = renderScriptRpy(PLANNER_FIXTURE, sb);
    expect(script).toMatch(/show sprite_\w+ at shake/);
  });

  it('accepts legacy free-string storyboards and still renders (M5 smoke-v5 compat)', () => {
    // Simulates M5's runtime/games/smoke-v5/workspace/storyboard.json shape.
    const legacy = {
      shots: [
        {
          shotNumber: 1,
          description: 'legacy shot from pre-v0.7 workspace',
          characters: ['白樱'],
          sceneName: 'sakura_night',
          staging: 'enter',
          transforms: 'stand breathing',
          transition: 'fade',
          effects: 'sakura particles',
          dialogueLines: [{ speaker: '白樱', text: '...' }],
        },
      ],
    } as unknown as StoryboarderOutput;
    const script = renderScriptRpy(PLANNER_FIXTURE, legacy);
    expect(script).toContain('label start:');
    expect(script).toMatch(/show sprite_\w+ at stand/);
    // sakura keyword in prose should still route to the particle overlay.
    expect(script).toContain('show sakura');
  });
});

describe('generateGameProject with UI patches', () => {
  it('appends UI patches to screens.rpy with marker comments', async () => {
    const files = await generateGameProject({
      planner: PLANNER_FIXTURE,
      storyboarder: STORYBOARDER_FIXTURE,
      uiPatches: [
        {
          screen: 'main_menu',
          patch: '# --- ui-patch: main_menu (mood: pastel) ---\nscreen main_menu():\n    pass',
        },
      ],
    });
    expect(files.screensRpy).toContain('# === renpy-agent UI patch: main_menu ===');
    expect(files.screensRpy).toContain('screen main_menu():');
  });

  it('leaves screens.rpy untouched when no UI patches are provided', async () => {
    const withNone = await generateGameProject({
      planner: PLANNER_FIXTURE,
      storyboarder: STORYBOARDER_FIXTURE,
    });
    const withEmpty = await generateGameProject({
      planner: PLANNER_FIXTURE,
      storyboarder: STORYBOARDER_FIXTURE,
      uiPatches: [],
    });
    expect(withNone.screensRpy).toBe(withEmpty.screensRpy);
    expect(withNone.screensRpy).not.toContain('renpy-agent UI patch');
  });
});
